import { useState } from 'preact/hooks'
import { ledgerNanoXPreview } from '../../signing/ledgerPreview.js'
import type { prepareDirectPayload } from '../../signing/backend.js'

export function LedgerScreenPreview({ payload }: { payload: ReturnType<typeof prepareDirectPayload> }) {
	const [rawMessages, setRawMessages] = useState(false)
	const [displayNonce, setDisplayNonce] = useState(false)
	const [displayHash, setDisplayHash] = useState(false)
	const [index, setIndex] = useState(0)
	const preview = ledgerNanoXPreview(payload, { rawMessages, displayNonce, displayHash })
	const currentIndex = Math.min(index, preview.screens.length - 1)
	const screen = preview.screens[currentIndex]
	return <section class = 'signing-panel ledger-preview'>
		<div><h2>Compare with your Ledger Nano X</h2><p class = 'signing-muted'>Expected screen content · Ethereum app 1.22.3</p></div>
		<p>This preview is generated by Interceptor. Verify the values on your physical device before approving. Line breaks and pagination may differ.</p>
		<div class = 'ledger-screen' aria-live = 'polite' aria-atomic = 'true'><strong>{ screen?.title }</strong>{ screen?.value === '' ? undefined : <span>{ screen?.value }</span> }</div>
		<div class = 'ledger-navigation'><button class = 'button signing-secondary' disabled = { currentIndex === 0 } onClick = { () => setIndex(currentIndex - 1) }>Previous</button><span>{ currentIndex + 1 } / { preview.screens.length }</span><button class = 'button signing-secondary' disabled = { currentIndex === preview.screens.length - 1 } onClick = { () => setIndex(currentIndex + 1) }>Next screen</button></div>
		<details><summary>Match your device settings</summary><p class = 'signing-muted'>These settings cannot be read from your Ledger. Set them here to match Ethereum’s App settings on the device; these controls only change this preview.</p>
			{ payload.method === 'eth_signTypedData_v4' ? <label class = 'ledger-setting'><input type = 'checkbox' checked = { rawMessages } onChange = { (event) => { setRawMessages(event.currentTarget.checked); setIndex(0) } }/>Raw messages</label> : undefined }
			{ payload.method === 'eth_sendTransaction' ? <label class = 'ledger-setting'><input type = 'checkbox' checked = { displayNonce } onChange = { (event) => { setDisplayNonce(event.currentTarget.checked); setIndex(0) } }/>Nonce</label> : undefined }
			<label class = 'ledger-setting'><input type = 'checkbox' checked = { displayHash } onChange = { (event) => { setDisplayHash(event.currentTarget.checked); setIndex(0) } }/>Transaction / message hash</label>
		</details>
		{ preview.notes.map((note) => <p key = { note } class = 'signing-muted'>{ note }</p>) }
	</section>
}
