// Static display metadata from Ledger Ethereum 1.22.3 src/network.c (Apache-2.0); see app/licenses/ledger-network.txt.
const networks: ReadonlyMap<bigint, Readonly<{ name: string, ticker: string }>> = new Map([
	[1n, { name: 'Ethereum', ticker: 'ETH' }],
	[3n, { name: 'Ropsten', ticker: 'ETH' }],
	[4n, { name: 'Rinkeby', ticker: 'ETH' }],
	[5n, { name: 'Goerli', ticker: 'ETH' }],
	[10n, { name: 'OP Mainnet', ticker: 'ETH' }],
	[14n, { name: 'Flare', ticker: 'FLR' }],
	[16n, { name: 'Flare Coston', ticker: 'FLR' }],
	[19n, { name: 'Songbird', ticker: 'SGB' }],
	[24n, { name: 'KardiaChain', ticker: 'KAI' }],
	[25n, { name: 'Cronos', ticker: 'CRO' }],
	[30n, { name: 'Rootstock', ticker: 'RBTC' }],
	[40n, { name: 'Telos EVM Mainnet', ticker: 'TLOS' }],
	[42n, { name: 'LUKSO', ticker: 'LYX' }],
	[50n, { name: 'XDC', ticker: 'XDC' }],
	[51n, { name: 'Apothemnetwork', ticker: 'TXDC' }],
	[56n, { name: 'BSC', ticker: 'BNB' }],
	[57n, { name: 'Syscoin', ticker: 'SYS' }],
	[61n, { name: 'Ethereum Classic', ticker: 'ETC' }],
	[66n, { name: 'OKXChain', ticker: 'OKT' }],
	[82n, { name: 'Meter', ticker: 'MTR' }],
	[99n, { name: 'POA', ticker: 'POA' }],
	[100n, { name: 'Gnosis', ticker: 'xDAI' }],
	[106n, { name: 'Velas EVM', ticker: 'VLX' }],
	[137n, { name: 'Polygon', ticker: 'POL' }],
	[138n, { name: 'Defi Oracle Meta', ticker: 'ETH' }],
	[146n, { name: 'Sonic', ticker: 'S' }],
	[196n, { name: 'OKBChain Mainnet', ticker: 'OKB' }],
	[199n, { name: 'BTTC', ticker: 'BTT' }],
	[246n, { name: 'EnergyWebChain', ticker: 'EWT' }],
	[248n, { name: 'Oasys', ticker: 'OAS' }],
	[250n, { name: 'Fantom', ticker: 'FTM' }],
	[288n, { name: 'Boba Network', ticker: 'ETH' }],
	[300n, { name: 'ZKsync Sepolia Testnet', ticker: 'ETH' }],
	[321n, { name: 'KCC', ticker: 'KCS' }],
	[324n, { name: 'ZKsync Era', ticker: 'ETH' }],
	[336n, { name: 'Shiden', ticker: 'SDN' }],
	[369n, { name: 'PulseChain', ticker: 'PLS' }],
	[592n, { name: 'Astar', ticker: 'ASTR' }],
	[888n, { name: 'Wanchain', ticker: 'WAN' }],
	[943n, { name: 'PulseChain Testnet', ticker: 'tPLS' }],
	[999n, { name: 'HyperEVM', ticker: 'HYPE' }],
	[1030n, { name: 'Conflux', ticker: 'CFX' }],
	[1088n, { name: 'Metis Andromeda', ticker: 'METIS' }],
	[1101n, { name: 'Polygon zkEVM', ticker: 'ETH' }],
	[1116n, { name: 'Core', ticker: 'CORE' }],
	[1135n, { name: 'Lisk', ticker: 'ETH' }],
	[1284n, { name: 'Moonbeam', ticker: 'GLMR' }],
	[1285n, { name: 'Moonriver', ticker: 'MOVR' }],
	[1329n, { name: 'Sei', ticker: 'SEI' }],
	[1818n, { name: 'Cube', ticker: 'CUBE' }],
	[1868n, { name: 'Soneium', ticker: 'ETH' }],
	[1907n, { name: 'Bitcichain', ticker: 'BITCI' }],
	[1923n, { name: 'Swellchain', ticker: 'ETH' }],
	[1924n, { name: 'Swellchain Testnet', ticker: 'ETH' }],
	[1946n, { name: 'Soneium Testnet Minato', ticker: 'ETH' }],
	[2222n, { name: 'Kava EVM', ticker: 'KAVA' }],
	[3776n, { name: 'Astar zkEVM', ticker: 'ETH' }],
	[4201n, { name: 'LUKSO Testnet', ticker: 'LYXt' }],
	[4202n, { name: 'Lisk Sepolia Testnet', ticker: 'ETH' }],
	[4689n, { name: 'IoTeX', ticker: 'IOTX' }],
	[4690n, { name: 'IoTeX Testnet', ticker: 'IOTX' }],
	[4919n, { name: 'Venidium', ticker: 'XVM' }],
	[5000n, { name: 'Mantle', ticker: 'MNT' }],
	[5003n, { name: 'Mantle Sepolia', ticker: 'MNT' }],
	[5165n, { name: 'Bahamut', ticker: 'FTN' }],
	[7000n, { name: 'ZetaChain', ticker: 'ZETA' }],
	[7171n, { name: 'Bitrock Mainnet', ticker: 'BROCK' }],
	[7341n, { name: 'Shyft', ticker: 'SHFT' }],
	[8217n, { name: 'Kaia Mainnet', ticker: 'KAIA' }],
	[8453n, { name: 'Base', ticker: 'ETH' }],
	[9001n, { name: 'Evmos', ticker: 'EVMOS' }],
	[10200n, { name: 'Chiado', ticker: 'xDAI' }],
	[10507n, { name: 'Numbers Protocol', ticker: 'NUM' }],
	[17000n, { name: 'Holesky', ticker: 'ETH' }],
	[39797n, { name: 'Energi', ticker: 'NRG' }],
	[42161n, { name: 'Arbitrum', ticker: 'ETH' }],
	[42220n, { name: 'Celo', ticker: 'CELO' }],
	[42793n, { name: 'Etherlink Mainnet', ticker: 'XTZ' }],
	[43114n, { name: 'Avalanche', ticker: 'AVAX' }],
	[44787n, { name: 'Celo Alfajores', ticker: 'aCELO' }],
	[47763n, { name: 'Neo X Mainnet', ticker: 'GAS' }],
	[52014n, { name: 'Electroneum', ticker: 'ETN' }],
	[59141n, { name: 'Linea Sepolia', ticker: 'ETH' }],
	[59144n, { name: 'Linea', ticker: 'ETH' }],
	[60808n, { name: 'BOB', ticker: 'ETH' }],
	[62320n, { name: 'Celo Baklava', ticker: 'bCELO' }],
	[62621n, { name: 'Multivac', ticker: 'MTV' }],
	[73799n, { name: 'Volta', ticker: 'VOLTA' }],
	[80094n, { name: 'Berachain', ticker: 'BERA' }],
	[81457n, { name: 'Blast', ticker: 'ETH' }],
	[84532n, { name: 'Base Sepolia', ticker: 'ETH' }],
	[153153n, { name: 'Odyssey Chain', ticker: 'DIONE' }],
	[200810n, { name: 'Bitlayer Testnet', ticker: 'BTC' }],
	[200901n, { name: 'Bitlayer', ticker: 'BTC' }],
	[421614n, { name: 'Arbitrum Sepolia', ticker: 'ETH' }],
	[534351n, { name: 'Scroll Sepolia', ticker: 'ETH' }],
	[534352n, { name: 'Scroll', ticker: 'ETH' }],
	[534353n, { name: 'Scroll Alpha', ticker: 'ETH' }],
	[543210n, { name: 'Zero', ticker: 'ETH' }],
	[5201420n, { name: 'Electroneum Testnet', ticker: 'ETN' }],
	[11155111n, { name: 'Sepolia', ticker: 'ETH' }],
	[11155420n, { name: 'OP Sepolia', ticker: 'ETH' }],
	[12227332n, { name: 'Neo X Testnet', ticker: 'GAS' }],
	[20531811n, { name: 'TecraTestnet', ticker: 'TCR' }],
	[20531812n, { name: 'Tecra', ticker: 'TCR' }],
	[168587773n, { name: 'Blast Sepolia', ticker: 'ETH' }],
	[245022926n, { name: 'Neon EVM Devnet', ticker: 'NEON' }],
	[245022934n, { name: 'Neon EVM Mainnet', ticker: 'NEON' }],
	[994873017n, { name: 'Lumia', ticker: 'LUMIA' }],
	[1666600000n, { name: 'Harmony ONE S0', ticker: 'ONE' }],
	[1666600001n, { name: 'Harmony ONE S1', ticker: 'ONE' }],
	[11297108109n, { name: 'Palm Network', ticker: 'PALM' }],
])

export function ledgerNetworkDisplay(chainId: bigint) {
	return networks.get(chainId) ?? { name: chainId.toString(), ticker: '???' }
}
