import { promises as fs } from 'node:fs'
import * as path from 'node:path'
import * as url from 'node:url'
import { INTERNAL_PROVIDER_METHODS } from '../app/ts/utils/internalProviderMethods.ts'

const projectRoot = path.join(path.dirname(url.fileURLToPath(import.meta.url)), '..')
const moduleOutputPath = path.join(projectRoot, 'app', 'ts', 'utils', 'internalProviderMethods.generated.ts')
const inpageSourcePath = path.join(projectRoot, 'app', 'inpage', 'ts', 'inpage.ts')
const generatedBlockPattern = /\/\/ GENERATED_INTERNAL_PROVIDER_METHODS_START[\s\S]*?\/\/ GENERATED_INTERNAL_PROVIDER_METHODS_END/
const formatMethodList = (methods: readonly string[]) => methods.map((method) => `\t'${ method }'`).join(',\n')

const inpageBlock = `// GENERATED_INTERNAL_PROVIDER_METHODS_START
const INTERNAL_BACKGROUND_METHODS = [
${ formatMethodList(INTERNAL_PROVIDER_METHODS) }
] as const

const isInternalBackgroundMethod = (method: string) => INTERNAL_BACKGROUND_METHODS.some((internalMethod) => internalMethod === method)
// GENERATED_INTERNAL_PROVIDER_METHODS_END`

const moduleContent = `// Generated by scripts/generate-inpage-internal-provider-methods.mts. Do not edit manually.
export const GENERATED_INTERNAL_PROVIDER_METHODS = [
${ formatMethodList(INTERNAL_PROVIDER_METHODS) }
] as const
`

const inpageSource = await fs.readFile(inpageSourcePath, 'utf8')
if (!generatedBlockPattern.test(inpageSource)) throw new Error('Could not find generated internal provider methods block in inpage.ts')

await Promise.all([
	fs.writeFile(inpageSourcePath, inpageSource.replace(generatedBlockPattern, inpageBlock)),
	fs.writeFile(moduleOutputPath, moduleContent),
])
