// Generated by scripts/generate-inpage-internal-provider-methods.mts. Do not edit manually.
export const GENERATED_INTERNAL_PROVIDER_METHODS = [
	'connected_to_signer',
	'eth_accounts_reply',
	'InterceptorError',
	'signer_chainChanged',
	'signer_reply',
	'wallet_switchEthereumChain_reply',
] as const
