name: Docker Image Build

on:
  pull_request:
    branches: [ main ]
jobs:
  job:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Build Extension
        working-directory: ./
        run: |
          docker image build --tag interceptor-extension .
          docker container create --name temp interceptor-extension
          docker container cp temp:/interceptor-firefox.zip .
          docker container cp temp:/interceptor-chrome.zip .
          docker container rm temp
