name: Docker Image Build

on:
  push:
    branches: [ test-workflow ]
jobs:
  job:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Test custom Extension
        uses: DarkFlorist/firefox-addon@master
        with:
          thing: 0

