on:
  push:
    branch:
      - 'release-test'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag
        run: |
          TAG=$(git tag --points-at HEAD | grep ^v)
          VERSION=${TAG#v}
          echo $TAG
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "VERSION=VERSION" >> $GITHUB_OUTPUT
          TAG=v0.0.57
          wget https://github.com/DarkFlorist/TheInterceptor/releases/download/$TAG/interceptor-firefox-$TAG.zip
#      - name: Upload Firefox Extension to Release
#        uses: actions/upload-release-asset@v1.0.1
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#            upload_url: ${{ steps.create_release.outputs.upload_url }}
#            asset_path: ./interceptor-firefox.zip
#            asset_name: interceptor-firefox-${{ steps.derive_tag.outputs.TAG }}.zip
#            asset_content_type: application/zip
