on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag
        run: |
          VERSION_FILE=extension/app/ts/version.ts
          MANIFEST_FILE_V2=extension/app/manifestV2.json
          MANIFEST_FILE_V3=extension/app/manifestV3.json
          GIT_COMMIT_SHA="${{ github.sha }}"
          TAG=$(basename "${{ github.ref }}")
          VERSION=${TAG#v}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo export const gitCommitSha = \"$GIT_COMMIT_SHA\" > $VERSION_FILE
          echo export const version = \"$VERSION\" >> $VERSION_FILE
          sed -i '/"version"/c\\t"version": "'$VERSION'",' $MANIFEST_FILE_V2 $MANIFEST_FILE_V3
      - name: Build Extension V2
        working-directory: ./extension
        run: |
          cp app/manifestV2.json app/manifest.json
          docker image build --tag interceptor-extension .
          docker container create --name temp interceptor-extension
          docker container cp temp:/extension/interceptor.zip /tmp/interceptor-v2.zip
          docker container rm temp
          zip /tmp/interceptor-source-v2.zip -r . -x '*.git*'
      - name: Build Extension V3
        working-directory: ./extension
        run: |
          cp app/manifestV3.json app/manifest.json
          docker image build --no-cache --tag interceptor-extension .
          docker container create --name temp interceptor-extension
          docker container cp temp:/extension/interceptor.zip ./interceptor-v3.zip
          docker container rm temp
          zip /tmp/interceptor-source-v3.zip -r . -x '*.git*' -x source.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.derive_tag.outputs.TAG }}
          release_name: ${{ steps.derive_tag.outputs.TAG }}
          draft: false
          prerelease: false
      - name: Upload V2 Extension to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension/interceptor-v2.zip
          asset_name: interceptor-v2-${{ steps.derive_tag.outputs.TAG }}.zip
          asset_content_type: application/zip
      - name: Upload V3 Extension to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension/interceptor-v3.zip
          asset_name: interceptor-v3-${{ steps.derive_tag.outputs.TAG }}.zip
          asset_content_type: application/zip
      - name: Upload Source to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source.zip
          asset_name: source-${{ steps.derive_tag.outputs.TAG }}.zip
          asset_content_type: application/zip
