on: 
  push: 
    branch: 
      - test-download
jobs: 
  release: 
    runs-on: ubuntu-latest 
    steps: 
      - id: download-release-asset
        name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ env.RELEASE }}
          file: myproject-${{ env.RELEASE }}.tar.gz
          target: release.tar.gz
          token: ${{ secrets.DEPLOY_TOKEN }}

